[build]
target = "wasm32-wasip1"
rustflags = [
    "-C",
    "target-feature=+bulk-memory",
    "-C",
    "link-args=--export malloc",
]

[target.wasm32-wasip1]
runner = "../../WasmEdge/build/tools/wasmedge/wasmedge"